# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 09:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), myapi.models.max_value_current_year])),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('file', models.FileField(blank=True, unique=True, upload_to='')),
                ('page', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description_of_book', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='publish_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='reader_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('read', 'read'), ('want_to_read', 'want_to_read'), ('in_progress', 'in_progress'), ('not_read', 'not_read')], default='not_read', max_length=12)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publish_house',
            field=models.ManyToManyField(to='myapi.publish_house'),
        ),
    ]
