# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_house',
        ),
        migrations.AddField(
            model_name='book',
            name='publish_house',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapi.publish_house'),
        ),
    ]
