# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200402_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='myapi.genre'),
        ),
    ]
