# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 12:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20200402_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
